### ISSUE TITLE
data does not seem to be checked in

### ISSUE THREAD

**Issue by mhlr** [ActivitySim/activitysim-estimation-example#1]
https://github.com/ActivitySim/activitysim-estimation-example/tree/main/data_sf/survey_data
![image](https://user-images.githubusercontent.com/1808573/232107209-e4eb0e02-461f-4fd0-8bd2-9cdd9874c725.png)

**Comment by jpn--** [comment]
Yes, [the data isn't checked in](https://github.com/ActivitySim/activitysim-estimation-example/tree/main/data_sf#the-data-isnt-here) for this repo.  The reason why this repo exists is to migrate away from large binary data files checked in to Git, and instead just attach the data as asset on a "[release](https://github.com/ActivitySim/activitysim-estimation-example/releases/tag/v0.0.2)".
